#!/bin/bash
# Flotilla Multi-Client Setup Commands
# This script provides the commands to run 2 clients and 1 server

echo "================================================"
echo "Flotilla: Running 2 Clients + 1 Server"
echo "================================================"
echo ""
echo "Run each command in a SEPARATE terminal window:"
echo ""
echo "### Terminal 1: Start MQTT Broker & Redis ###"
echo "cd /home/snowden/Desktop/flotilla/docker && docker-compose up -d"
echo ""
echo "### Terminal 2: Start Server ###"
echo "cd /home/snowden/Desktop/flotilla/src && ../.venv/bin/python flo_server.py"
echo ""
echo "### Terminal 3: Start Client 1 ###"
echo "cd /home/snowden/Desktop/flotilla/src && ../.venv/bin/python flo_client.py --client-num 1"
echo ""
echo "### Terminal 4: Start Client 2 ###"
echo "cd /home/snowden/Desktop/flotilla/src && ../.venv/bin/python flo_client.py --client-num 2"
echo ""
echo "### Terminal 5: Start Training Session (Optional) ###"
echo "cd /home/snowden/Desktop/flotilla/src && ../.venv/bin/python flo_session.py ../config/flotilla_quicksetup_config.yaml --federated_server_endpoint localhost:12345"
echo ""
echo "================================================"
echo "Expected Behavior:"
echo "- Client 1: temp_1/, MQTT 'workstation_1', Ports 50053/50054"
echo "- Client 2: temp_2/, MQTT 'workstation_2', Ports 50055/50056"
echo "- NO MQTT reconnection loops!"
echo "- NO Address already in use errors!"
echo "- Both clients participate in federated learning"
echo "================================================"
